use_frameworks!

platform :ios, '10.0'

target 'OchornmaCocoaLesson_Example' do
  pod 'OchornmaCocoaLesson', :path => '../'

  target 'OchornmaCocoaLesson_Tests' do
    inherit! :search_paths

    
  end
end
